server:
  port: 8090
  compression:
    enabled: true
  connection-timeout: 3000

spring:
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置 默认为true，生产环境应该设置为true
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
      
  messages:
    basename: i18n.messages #配置国际化properties文件路径，放在classpath的i18n文件夹，文件前缀为messages